name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm test
